name: Build and publish NoSQL 19.5-ce container image to GitHub Container Registry

on:
  push:
    branches:
      - main
    paths:
      - 'NoSQL/19.5-ce/*'

env:
  IMAGE_NAME: nosql
  TAG: 19.5-ce

jobs:
  push:
    name: Build and push NoSQL 19.5-ce image
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u "${GITHUB_ACTOR,,}" --password-stdin ghcr.io

      - name: Build NoSQL 19.5-ce image
        run: |
          cd NoSQL/19.5-ce
          docker build --tag "ghcr.io/${GITHUB_ACTOR,,}/$IMAGE_NAME:$TAG" .

      - name: Push image to GitHub Container Registry
        run: |
          docker push "ghcr.io/${GITHUB_ACTOR,,}/$IMAGE_NAME:$TAG"
